contains() and containsAll() methods added
AplesinEducation/ApelsinEducationProject pull request #6
Opened 2022-07-20 07:42 UTC by Zulfiya5

2022-07-20 10:01 UTC, com-sultanov-roman requested changes

2022-07-20 10:01 UTC, com-sultanov-roman commented on src/main/java/org/apelsin/tutorial/collections/ArrayCollection.java
> +    public void insert(Object item) {
It is better to rename insert() method as pushBack() as it is more intuitively clear

2022-07-20 10:01 UTC, com-sultanov-roman commented on src/main/java/org/apelsin/tutorial/collections/ArrayCollection.java
> +            Object[] newContent = new Object[capacity * 2];
it is better to extract resize logic to another method

2022-07-20 11:23 UTC, com-sultanov-roman approved these changes

2022-07-22 05:19 UTC, xtreme-uz commented on src/main/java/org/apelsin/tutorial/collections/ArrayCollection.java
> +    public boolean contains(Object value) {
What about null value, it is not null safe

2022-07-22 05:28 UTC, xtreme-uz commented on src/main/java/org/apelsin/tutorial/collections/ArrayCollection.java
> +    public void doubleContentLengthIfCapacityIsReached() {
`capacity` should also be changed

2022-07-22 05:37 UTC, xtreme-uz commented on src/main/java/org/apelsin/tutorial/collections/ArrayCollection.java
> +    public void doubleContentLengthIfCapacityIsReached() {
You used `capacity` as `size` of array, check you logic

2022-07-22 10:43 UTC, MurodDevUzb commented on src/main/java/org/apelsin/tutorial/collections/ArrayCollection.java
> +        for (int i = 0; i < capacity; i++) {
Почему до capacity проверяем

2022-07-25 18:05 UTC, dostonbokhodirov approved these changes

2022-07-26 07:55 UTC, nurmukhammadsunatullaev approved these changes

2022-07-26 07:55 UTC, merged